// Add any additional repositories for your dependencies here.
repositories {
    mavenLocal()
    flatDir {
        dirs 'libs'
    }
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        name = 'mavenpattern'
        url = 'https://mvn.falsepattern.com/releases'
        content {
            includeGroup 'com.falsepattern'
        }
    }
}
